country_balls_amount = 10
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-57, 232, 56, 326],
                "x": 0,
                "y": 335,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-64, -109, 69, -10],
                "x": 4,
                "y": 0,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 0, "y": 787, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [931, 526, 1057, 626],
                "x": 1000,
                "y": 616,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [936, 135, 1062, 238],
                "x": 1000,
                "y": 244,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [894, -96, 1010, -3],
                "x": 952,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-51, -84, 70, 19],
                "x": 0,
                "y": 10,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-53, 533, 61, 618],
                "x": 0,
                "y": 627,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [-59, 223, 60, 334],
                "x": 0,
                "y": 331,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-55, 62, 63, 154],
                "x": 0,
                "y": 160,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-16, 278, 84, 380],
                "x": 34,
                "y": 374,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 3, "y": 14, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-36, 633, 72, 741],
                "x": 21,
                "y": 735,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 977, "y": 590, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 997, "y": 265, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 942, "y": 76, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [-57, -67, 57, 29],
                "x": 0,
                "y": 29,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-54, 508, 66, 617],
                "x": 0,
                "y": 610,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 30, "y": 320, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [-45, 101, 81, 205],
                "x": 21,
                "y": 209,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-2, 318, 130, 405],
                "x": 68,
                "y": 409,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-51, -68, 63, 22],
                "x": 3,
                "y": 28,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-24, 583, 102, 685],
                "x": 42,
                "y": 686,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 955, "y": 566, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [935, 188, 1056, 290],
                "x": 995,
                "y": 286,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [879, 51, 982, 139],
                "x": 932,
                "y": 145,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-56, -55, 57, 45],
                "x": 1,
                "y": 49,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 0, "y": 594, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 60, "y": 310, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [-18, 147, 111, 246],
                "x": 43,
                "y": 254,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [53, 333, 173, 429],
                "x": 103,
                "y": 439,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-51, -54, 57, 43],
                "x": 3,
                "y": 43,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [7, 542, 116, 630],
                "x": 63,
                "y": 640,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [880, 441, 998, 550],
                "x": 933,
                "y": 542,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [931, 200, 1046, 305],
                "x": 992,
                "y": 306,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [866, 100, 985, 203],
                "x": 922,
                "y": 208,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-66, -42, 55, 78],
                "x": 2,
                "y": 68,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-65, 477, 57, 583],
                "x": 0,
                "y": 578,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [30, 204, 140, 308],
                "x": 90,
                "y": 301,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 65, "y": 295, "track_id": None},
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [75, 376, 204, 472],
                "x": 137,
                "y": 466,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 3, "y": 57, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [35, 487, 143, 586],
                "x": 85,
                "y": 596,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [849, 411, 971, 528],
                "x": 911,
                "y": 520,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [920, 219, 1041, 336],
                "x": 990,
                "y": 326,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [854, 165, 981, 273],
                "x": 913,
                "y": 264,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-65, -4, 72, 80],
                "x": 2,
                "y": 87,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-56, 472, 60, 567],
                "x": 0,
                "y": 562,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [68, 200, 176, 300],
                "x": 121,
                "y": 292,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [19, 230, 151, 327],
                "x": 86,
                "y": 332,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 172, "y": 489, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-66, -35, 56, 71],
                "x": 3,
                "y": 72,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [54, 449, 161, 549],
                "x": 106,
                "y": 555,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 888, "y": 499, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [930, 238, 1039, 338],
                "x": 988,
                "y": 345,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [836, 214, 963, 320],
                "x": 903,
                "y": 314,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-60, 11, 71, 104],
                "x": 3,
                "y": 106,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-53, 450, 60, 550],
                "x": 0,
                "y": 545,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [101, 191, 221, 295],
                "x": 151,
                "y": 285,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [38, 255, 160, 366],
                "x": 108,
                "y": 365,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [148, 399, 264, 511],
                "x": 206,
                "y": 508,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 3, "y": 86, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [75, 413, 178, 515],
                "x": 127,
                "y": 516,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [800, 376, 933, 478],
                "x": 866,
                "y": 478,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [924, 264, 1043, 359],
                "x": 985,
                "y": 365,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [831, 266, 949, 352],
                "x": 893,
                "y": 358,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-58, 28, 71, 116],
                "x": 4,
                "y": 125,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-53, 425, 56, 533],
                "x": 0,
                "y": 529,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [127, 182, 240, 278],
                "x": 181,
                "y": 278,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [60, 291, 186, 391],
                "x": 130,
                "y": 394,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [188, 415, 304, 533],
                "x": 241,
                "y": 524,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-64, 8, 71, 101],
                "x": 3,
                "y": 101,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [84, 371, 218, 478],
                "x": 148,
                "y": 479,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [793, 353, 895, 463],
                "x": 844,
                "y": 459,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [919, 275, 1034, 374],
                "x": 983,
                "y": 383,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [813, 297, 952, 402],
                "x": 883,
                "y": 396,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-60, 44, 66, 147],
                "x": 4,
                "y": 144,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-67, 422, 50, 522],
                "x": 0,
                "y": 513,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [162, 180, 272, 280],
                "x": 212,
                "y": 273,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [96, 315, 209, 412],
                "x": 152,
                "y": 420,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 275, "y": 536, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-56, 7, 57, 124],
                "x": 3,
                "y": 115,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [115, 347, 222, 452],
                "x": 170,
                "y": 444,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [764, 339, 886, 449],
                "x": 822,
                "y": 441,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 981, "y": 402, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [819, 320, 933, 436],
                "x": 874,
                "y": 429,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-55, 64, 59, 161],
                "x": 5,
                "y": 163,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-59, 391, 65, 493],
                "x": 0,
                "y": 497,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [180, 159, 309, 272],
                "x": 242,
                "y": 268,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [108, 339, 242, 449],
                "x": 173,
                "y": 442,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 310, "y": 545, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 3, "y": 129, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [125, 322, 246, 422],
                "x": 191,
                "y": 412,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 800, "y": 424, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [921, 312, 1036, 412],
                "x": 978,
                "y": 420,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [809, 351, 914, 459],
                "x": 864,
                "y": 456,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-55, 91, 71, 185],
                "x": 6,
                "y": 181,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-50, 380, 52, 474],
                "x": 0,
                "y": 481,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [213, 158, 329, 255],
                "x": 272,
                "y": 265,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [139, 366, 256, 470],
                "x": 195,
                "y": 462,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 344, "y": 551, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-65, 37, 71, 135],
                "x": 3,
                "y": 144,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [143, 292, 279, 384],
                "x": 212,
                "y": 382,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 777, "y": 408, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 976, "y": 439, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [797, 371, 911, 472],
                "x": 854,
                "y": 479,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-45, 109, 62, 200],
                "x": 7,
                "y": 199,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-70, 374, 58, 462],
                "x": 0,
                "y": 465,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [251, 165, 369, 263],
                "x": 303,
                "y": 263,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [161, 376, 285, 472],
                "x": 217,
                "y": 478,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [327, 444, 438, 544],
                "x": 379,
                "y": 554,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-66, 54, 73, 148],
                "x": 3,
                "y": 158,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 234, "y": 355, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [701, 295, 816, 393],
                "x": 755,
                "y": 393,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 973, "y": 456, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [786, 387, 898, 503],
                "x": 844,
                "y": 496,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 7, "y": 218, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [-66, 342, 64, 444],
                "x": 0,
                "y": 449,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [263, 168, 388, 255],
                "x": 333,
                "y": 263,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [173, 387, 298, 492],
                "x": 239,
                "y": 492,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [350, 461, 464, 548],
                "x": 413,
                "y": 554,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 3, "y": 173, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [195, 236, 312, 325],
                "x": 255,
                "y": 329,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [672, 275, 787, 373],
                "x": 733,
                "y": 379,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [912, 364, 1030, 474],
                "x": 971,
                "y": 474,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [770, 404, 891, 513],
                "x": 835,
                "y": 508,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-45, 145, 78, 230],
                "x": 8,
                "y": 236,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-70, 334, 53, 431],
                "x": 0,
                "y": 432,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [304, 162, 427, 254],
                "x": 363,
                "y": 263,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [192, 399, 327, 499],
                "x": 260,
                "y": 503,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [383, 450, 509, 546],
                "x": 448,
                "y": 551,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-50, 85, 59, 186],
                "x": 2,
                "y": 187,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [223, 209, 336, 305],
                "x": 276,
                "y": 306,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [643, 259, 764, 363],
                "x": 711,
                "y": 365,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [910, 386, 1028, 481],
                "x": 969,
                "y": 491,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [757, 423, 895, 523],
                "x": 825,
                "y": 516,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-48, 162, 74, 245],
                "x": 9,
                "y": 254,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-50, 315, 62, 417],
                "x": 0,
                "y": 416,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [337, 156, 449, 263],
                "x": 393,
                "y": 266,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 282, "y": 511, "track_id": None},
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [426, 439, 534, 540],
                "x": 482,
                "y": 546,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-48, 93, 62, 195],
                "x": 2,
                "y": 202,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 297, "y": 285, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [620, 263, 754, 344],
                "x": 688,
                "y": 353,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 966, "y": 508, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [750, 428, 874, 523],
                "x": 815,
                "y": 520,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-41, 168, 66, 272],
                "x": 9,
                "y": 272,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-55, 307, 67, 407],
                "x": 0,
                "y": 400,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [367, 168, 482, 271],
                "x": 424,
                "y": 269,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 304, "y": 518, "track_id": None},
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [463, 444, 577, 529],
                "x": 517,
                "y": 539,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-54, 116, 70, 206],
                "x": 2,
                "y": 216,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [264, 158, 379, 273],
                "x": 319,
                "y": 266,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 666, "y": 342, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [910, 432, 1022, 521],
                "x": 964,
                "y": 524,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [745, 409, 869, 529],
                "x": 805,
                "y": 519,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 10, "y": 289, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 0, "y": 384, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [392, 166, 520, 268],
                "x": 454,
                "y": 274,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [276, 418, 390, 512],
                "x": 326,
                "y": 522,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [495, 430, 612, 519],
                "x": 551,
                "y": 529,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-58, 127, 66, 236],
                "x": 2,
                "y": 231,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 340, "y": 249, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [592, 239, 694, 338],
                "x": 644,
                "y": 332,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [911, 439, 1022, 544],
                "x": 962,
                "y": 541,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [741, 408, 850, 516],
                "x": 796,
                "y": 515,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-55, 204, 61, 312],
                "x": 11,
                "y": 307,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 0, "y": 368, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 484, "y": 281, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [280, 434, 405, 517],
                "x": 347,
                "y": 525,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [529, 408, 651, 527],
                "x": 586,
                "y": 518,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 2, "y": 245, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [303, 137, 431, 230],
                "x": 361,
                "y": 234,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [553, 233, 689, 329],
                "x": 622,
                "y": 323,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [889, 465, 1019, 558],
                "x": 959,
                "y": 557,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [736, 416, 839, 516],
                "x": 786,
                "y": 506,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-58, 234, 74, 324],
                "x": 12,
                "y": 324,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 0, "y": 352, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 515, "y": 290, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [303, 429, 431, 525],
                "x": 369,
                "y": 526,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [561, 411, 687, 494],
                "x": 620,
                "y": 504,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-66, 157, 55, 263],
                "x": 2,
                "y": 260,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [324, 123, 447, 212],
                "x": 382,
                "y": 221,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [548, 206, 652, 312],
                "x": 600,
                "y": 314,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [901, 478, 1022, 582],
                "x": 957,
                "y": 573,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [714, 405, 827, 498],
                "x": 776,
                "y": 495,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-42, 232, 70, 351],
                "x": 12,
                "y": 342,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-53, 237, 59, 343],
                "x": 0,
                "y": 336,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [488, 193, 604, 301],
                "x": 545,
                "y": 300,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [325, 433, 454, 521],
                "x": 391,
                "y": 526,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 655, "y": 489, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 2, "y": 275, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [343, 120, 473, 214],
                "x": 404,
                "y": 210,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [523, 211, 636, 303],
                "x": 577,
                "y": 307,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 954, "y": 588, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [708, 372, 821, 474],
                "x": 767,
                "y": 480,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 13, "y": 359, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [-51, 215, 68, 324],
                "x": 0,
                "y": 320,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [509, 207, 630, 321],
                "x": 575,
                "y": 313,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [344, 418, 474, 523],
                "x": 413,
                "y": 524,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [639, 366, 752, 464],
                "x": 689,
                "y": 472,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-64, 197, 59, 290],
                "x": 2,
                "y": 289,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [363, 109, 485, 199],
                "x": 425,
                "y": 202,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [498, 199, 618, 305],
                "x": 555,
                "y": 301,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 952, "y": 603, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 757, "y": 462, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [-40, 272, 83, 376],
                "x": 14,
                "y": 376,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-68, 214, 71, 312],
                "x": 1,
                "y": 304,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [543, 226, 667, 322],
                "x": 606,
                "y": 327,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [374, 419, 489, 524],
                "x": 434,
                "y": 522,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [667, 364, 794, 449],
                "x": 724,
                "y": 454,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-64, 202, 71, 301],
                "x": 2,
                "y": 304,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [389, 92, 501, 197],
                "x": 446,
                "y": 195,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [475, 205, 594, 300],
                "x": 533,
                "y": 295,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [893, 516, 1003, 620],
                "x": 950,
                "y": 618,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [692, 334, 798, 436],
                "x": 747,
                "y": 441,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-49, 302, 83, 393],
                "x": 14,
                "y": 393,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 1, "y": 288, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [573, 249, 689, 335],
                "x": 636,
                "y": 343,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [404, 428, 515, 508],
                "x": 456,
                "y": 518,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 758, "y": 434, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-54, 221, 69, 317],
                "x": 2,
                "y": 318,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [410, 91, 530, 185],
                "x": 468,
                "y": 190,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 511, "y": 290, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [896, 539, 1001, 639],
                "x": 947,
                "y": 633,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [675, 325, 800, 410],
                "x": 737,
                "y": 417,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-55, 307, 72, 405],
                "x": 15,
                "y": 409,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-66, 164, 52, 277],
                "x": 1,
                "y": 271,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [605, 271, 719, 366],
                "x": 666,
                "y": 361,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 478, "y": 514, "track_id": None},
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [737, 321, 853, 417],
                "x": 793,
                "y": 413,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-57, 238, 61, 339],
                "x": 2,
                "y": 333,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [427, 88, 558, 185],
                "x": 489,
                "y": 187,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [418, 188, 557, 279],
                "x": 488,
                "y": 287,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [879, 539, 1012, 639],
                "x": 945,
                "y": 647,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [666, 296, 782, 388],
                "x": 728,
                "y": 391,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 16, "y": 426, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [-58, 158, 66, 256],
                "x": 1,
                "y": 255,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [645, 285, 762, 386],
                "x": 696,
                "y": 381,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [444, 408, 555, 508],
                "x": 500,
                "y": 510,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [764, 289, 881, 401],
                "x": 827,
                "y": 392,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 2, "y": 347, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 510, "y": 186, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [411, 182, 535, 284],
                "x": 466,
                "y": 284,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [890, 558, 1009, 666],
                "x": 943,
                "y": 661,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [666, 258, 773, 353],
                "x": 718,
                "y": 362,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-39, 338, 73, 436],
                "x": 17,
                "y": 443,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-64, 136, 58, 241],
                "x": 1,
                "y": 239,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [661, 307, 790, 406],
                "x": 727,
                "y": 404,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 521, "y": 505, "track_id": None},
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [793, 274, 928, 375],
                "x": 862,
                "y": 369,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-66, 256, 54, 359],
                "x": 1,
                "y": 362,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 531, "y": 187, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [383, 188, 494, 282],
                "x": 444,
                "y": 282,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [888, 572, 1001, 684],
                "x": 940,
                "y": 675,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [646, 237, 764, 333],
                "x": 708,
                "y": 332,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-44, 363, 86, 465],
                "x": 17,
                "y": 459,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-61, 113, 70, 230],
                "x": 1,
                "y": 223,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [701, 328, 822, 439],
                "x": 757,
                "y": 429,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [488, 398, 609, 490],
                "x": 543,
                "y": 500,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [836, 245, 955, 342],
                "x": 896,
                "y": 346,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-60, 282, 68, 377],
                "x": 1,
                "y": 377,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 553, "y": 190, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [360, 181, 477, 274],
                "x": 422,
                "y": 281,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [878, 591, 1006, 694],
                "x": 938,
                "y": 689,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [644, 202, 761, 307],
                "x": 698,
                "y": 300,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-35, 371, 70, 472],
                "x": 18,
                "y": 475,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-55, 115, 59, 197],
                "x": 1,
                "y": 207,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [721, 346, 847, 453],
                "x": 787,
                "y": 456,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [498, 403, 628, 485],
                "x": 565,
                "y": 495,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 931, "y": 323, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-49, 296, 57, 384],
                "x": 1,
                "y": 391,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [511, 101, 641, 201],
                "x": 574,
                "y": 194,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [349, 173, 461, 282],
                "x": 400,
                "y": 281,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [868, 592, 1004, 701],
                "x": 935,
                "y": 702,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [638, 158, 739, 272],
                "x": 689,
                "y": 266,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 19, "y": 491, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 1, "y": 191, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 818, "y": 485, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [522, 396, 645, 487],
                "x": 586,
                "y": 490,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [899, 201, 1035, 290],
                "x": 965,
                "y": 299,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-59, 300, 55, 399],
                "x": 1,
                "y": 406,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [542, 110, 649, 197],
                "x": 595,
                "y": 200,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [313, 183, 439, 272],
                "x": 377,
                "y": 282,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 933, "y": 715, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 679, "y": 230, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [-47, 406, 77, 502],
                "x": 19,
                "y": 507,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 1, "y": 175, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [781, 408, 911, 507],
                "x": 848,
                "y": 517,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [551, 383, 660, 496],
                "x": 608,
                "y": 486,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [940, 169, 1056, 282],
                "x": 1000,
                "y": 275,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-63, 328, 68, 418],
                "x": 1,
                "y": 420,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [552, 98, 683, 205],
                "x": 617,
                "y": 208,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 355, "y": 284, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [879, 622, 995, 733],
                "x": 931,
                "y": 728,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [604, 84, 720, 185],
                "x": 669,
                "y": 194,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-30, 426, 90, 532],
                "x": 20,
                "y": 523,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-52, 61, 66, 169],
                "x": 1,
                "y": 159,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [811, 444, 936, 551],
                "x": 878,
                "y": 551,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [575, 382, 687, 486],
                "x": 630,
                "y": 483,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 1, "y": 435, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 638, "y": 218, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 333, "y": 286, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [872, 648, 983, 737],
                "x": 928,
                "y": 741,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [605, 58, 712, 162],
                "x": 659,
                "y": 156,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-35, 437, 88, 532],
                "x": 21,
                "y": 539,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 1, "y": 143, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [856, 496, 972, 579],
                "x": 909,
                "y": 588,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [582, 385, 703, 485],
                "x": 652,
                "y": 481,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 1, "y": 450, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 659, "y": 230, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 311, "y": 289, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [868, 653, 977, 754],
                "x": 926,
                "y": 753,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 650, "y": 118, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [-36, 455, 82, 544],
                "x": 21,
                "y": 554,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-56, 30, 68, 122],
                "x": 1,
                "y": 127,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 939, "y": 628, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [603, 379, 728, 472],
                "x": 673,
                "y": 479,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-66, 368, 70, 461],
                "x": 1,
                "y": 464,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 680, "y": 243, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 288, "y": 294, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [855, 658, 988, 767],
                "x": 924,
                "y": 765,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [590, -12, 694, 82],
                "x": 640,
                "y": 79,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 22, "y": 570, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [-62, 15, 63, 114],
                "x": 1,
                "y": 111,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [910, 573, 1022, 666],
                "x": 969,
                "y": 670,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 695, "y": 479, "track_id": None},
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-54, 374, 56, 477],
                "x": 1,
                "y": 479,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [632, 149, 753, 250],
                "x": 702,
                "y": 258,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 266, "y": 299, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [859, 675, 987, 773],
                "x": 921,
                "y": 777,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [579, -51, 698, 31],
                "x": 630,
                "y": 39,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 23, "y": 585, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [-61, -9, 61, 105],
                "x": 1,
                "y": 95,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [940, 617, 1051, 718],
                "x": 1000,
                "y": 716,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [663, 370, 777, 483],
                "x": 717,
                "y": 480,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-60, 388, 65, 497],
                "x": 1,
                "y": 494,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 723, "y": 274, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 244, "y": 305, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [862, 689, 975, 786],
                "x": 919,
                "y": 788,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [570, -106, 673, 8],
                "x": 621,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-41, 505, 76, 602],
                "x": 24,
                "y": 600,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-49, -12, 57, 83],
                "x": 1,
                "y": 79,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [673, 387, 809, 491],
                "x": 739,
                "y": 483,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-51, 401, 59, 509],
                "x": 1,
                "y": 508,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [687, 188, 802, 297],
                "x": 744,
                "y": 292,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [163, 208, 286, 304],
                "x": 222,
                "y": 311,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [867, 708, 983, 809],
                "x": 917,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-43, 523, 86, 614],
                "x": 24,
                "y": 615,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-60, -32, 66, 58],
                "x": 1,
                "y": 63,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [695, 382, 827, 491],
                "x": 760,
                "y": 488,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-65, 432, 68, 514],
                "x": 1,
                "y": 523,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [712, 222, 834, 309],
                "x": 765,
                "y": 312,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 200, "y": 319, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [-36, 534, 94, 626],
                "x": 25,
                "y": 630,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 1, "y": 47, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [724, 384, 849, 497],
                "x": 782,
                "y": 494,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-63, 441, 63, 532],
                "x": 0,
                "y": 538,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [719, 227, 855, 339],
                "x": 787,
                "y": 333,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [107, 233, 238, 337],
                "x": 177,
                "y": 327,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 26, "y": 645, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [-52, -76, 56, 39],
                "x": 1,
                "y": 31,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [738, 397, 863, 512],
                "x": 804,
                "y": 503,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-57, 443, 67, 549],
                "x": 0,
                "y": 552,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [741, 250, 858, 351],
                "x": 808,
                "y": 356,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [86, 227, 217, 340],
                "x": 155,
                "y": 336,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 26, "y": 660, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [-60, -88, 51, 21],
                "x": 1,
                "y": 15,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 826, "y": 514, "track_id": None},
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-59, 464, 64, 572],
                "x": 0,
                "y": 567,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [775, 275, 888, 381],
                "x": 829,
                "y": 380,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 133, "y": 346, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [-36, 571, 97, 667],
                "x": 27,
                "y": 674,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 2, "y": 0, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [789, 421, 906, 529],
                "x": 847,
                "y": 528,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 0, "y": 582, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 851, "y": 406, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [44, 250, 177, 359],
                "x": 111,
                "y": 357,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 28, "y": 689, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [802, 451, 921, 535],
                "x": 869,
                "y": 545,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-67, 506, 52, 599],
                "x": 0,
                "y": 597,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [811, 337, 922, 426],
                "x": 872,
                "y": 433,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [34, 268, 158, 370],
                "x": 88,
                "y": 368,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-31, 602, 90, 710],
                "x": 29,
                "y": 703,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [833, 457, 941, 555],
                "x": 891,
                "y": 565,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-63, 507, 51, 603],
                "x": 0,
                "y": 611,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [830, 353, 958, 469],
                "x": 893,
                "y": 461,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [1, 284, 118, 382],
                "x": 66,
                "y": 380,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 29, "y": 717, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [855, 478, 976, 596],
                "x": 913,
                "y": 587,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-51, 535, 67, 634],
                "x": 0,
                "y": 626,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 914, "y": 491, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-12, 285, 111, 384],
                "x": 44,
                "y": 393,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 30, "y": 731, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [878, 504, 1003, 610],
                "x": 934,
                "y": 613,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 0, "y": 641, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [880, 429, 1003, 523],
                "x": 936,
                "y": 523,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-45, 299, 89, 413],
                "x": 22,
                "y": 407,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-19, 652, 88, 739],
                "x": 31,
                "y": 745,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [889, 547, 1019, 639],
                "x": 956,
                "y": 643,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-65, 556, 51, 663],
                "x": 0,
                "y": 655,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 957, "y": 555, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-65, 312, 50, 426],
                "x": 0,
                "y": 422,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-39, 658, 87, 758],
                "x": 31,
                "y": 759,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [925, 571, 1029, 676],
                "x": 978,
                "y": 676,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 0, "y": 670, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [912, 499, 1034, 586],
                "x": 978,
                "y": 589,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-32, 675, 91, 778],
                "x": 32,
                "y": 773,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 1000, "y": 714, "track_id": None},
        ],
    },
    {
        "frame_id": 48,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-70, 576, 67, 692],
                "x": 0,
                "y": 685,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 1000, "y": 625, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [-28, 684, 86, 795],
                "x": 33,
                "y": 786,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 49,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-68, 602, 55, 707],
                "x": 0,
                "y": 700,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-34, 696, 99, 790],
                "x": 34,
                "y": 800,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 50,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [-58, 605, 60, 708],
                "x": 0,
                "y": 715,
                "track_id": None,
            }
        ],
    },
]
